#Php ini attributes
default['jolicode-php']['config']['date.timezone']       = "Europe/Paris"
default['jolicode-php']['config']['max_execution_time']  = "0"
default['jolicode-php']['config']['memory_limit']        = "-1"
default['jolicode-php']['config']['html_errors']         = "Off"
default['jolicode-php']['config']['display_errors']      = "Off"
default['jolicode-php']['config']['upload_max_filesize'] = "2M"
default['jolicode-php']['config']['post_max_size']       = "8M"
default['jolicode-php']['config']['error_log']           = ""