name             "jolicode-php_test"
maintainer       "JoliCode"
maintainer_email "jwurtz@jolicode.com"
license          "Apache 2.0"
description      "Used to test the jolicode-php cookbook"
version          "1.0.0"

depends "jolicode-php"
depends "zeromq"
depends "nginx", "~> 1.6.0"